apiVersion: apps/v1
kind: Deployment
metadata:
  name: anaconda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anaconda
  template:
    metadata:
      labels:
        app: anaconda
    spec:
      containers:
      - name: anaconda
        image: continuumio/anaconda3
        command: ["/bin/bash", "-c"]
        args:
          - |
            conda install jupyter -y &&
            jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: anaconda-service
spec:
  type: NodePort
  selector:
    app: anaconda
  ports:
    - port: 8888
      nodePort: 30000  # Porta no seu Windows (30000-32767)
